### ISSUE TITLE
Where is HexapawnZero code

### ISSUE THREAD

**Issue by brianprichardson** [asdfjkl/neural_network_chess#2]
"from HexapawnZero.common.game import Board"

I've searched for the code and cannot find it.

Thank you for your great work.

**Comment by asdfjkl** [comment]
https://github.com/asdfjkl/neural_network_chess/blob/main/chapter_04/common/game.py

I will update the path's later today...

**Comment by asdfjkl** [comment]
Apologies. That code was indeed difficult to run without an IDE. I've changed this to a flat directory structure and added a README.txt so that it should be more clear how to get the example running and what each file does.
