### ISSUE TITLE
Chapter 2 convolution.py

### ISSUE THREAD

**Issue by d-kraft** [asdfjkl/neural_network_chess#6]
Hello Dominik,
I'm a Python novice, but an experienced chess player and long ago a developer of software for infinite dimensional optimization.
I've installed the latest Python on a 64 cores Ryzen Threadripper with two NVIDIA 3090 graphic cards.
I study your very helpful overview of modern chess engine programming and started with Chapter 2 where except convolution.py
all examples work fine.
I have installed module scikit-image as skimage  doesn't load correctly.
Then (without changing the source of convolution.py) I get the following warning

> PS C:\Users\diete\Downloads\neural_network_chess-1.3\chapter_02> python.exe .\convolution.py
(640, 480)
Lossy conversion from float64 to uint8. Range [-377.0, 433.0]. Convert image to uint8 prior to saving to suppress this warning.
PS C:\Users\diete\Downloads\neural_network_chess-1.3\chapter_02>

and after some seconds python exits without any more output.
Help with this problem is kindly appreciated.
Dieter

**Comment by asdfjkl** [comment]
That warning can be ignored.
After running the script there is no additional output. 
What the code does ist to take `bainman.jpg` as input and create and save the image `baikinman_filter_no_thresh.png`. You can verify that everything works by deleting `baikinman_filter_no_thresh.png` prior to running the script
