### ISSUE TITLE
# Tabula Rasa Learning Approach Proposal

### ISSUE THREAD

**Issue by severeduck** [asdfjkl/neural_network_chess#9]
# Tabula Rasa Learning Approach Proposal

## Summary
I propose implementing a "Tabula Rasa" (clean slate) learning approach for our project, where the system starts with minimal prior knowledge and learns from scratch through self-play or self-improvement mechanisms. This approach aims to allow the system to develop its own understanding and strategies organically.

## Background
In many AI systems, predefined heuristics, rule-based algorithms, or human-designed features are used to guide the learning or decision-making process. However, alternative approaches, such as "Tabula Rasa," offer the opportunity to build intelligence without initial biases or predefined rules.

## Proposal
The idea is to:
- Create a framework where the system begins with minimal or no initial knowledge.
- Develop mechanisms for self-play, exploration, or learning from experience.
- Allow the system to adapt, optimize, and evolve its strategies over time.
- Potentially discover novel approaches, solutions, or insights that may not be apparent with traditional methods.

## Potential Benefits
- **Innovation**: This approach may lead to the discovery of unconventional solutions or strategies.
- **Adaptability**: The system can adapt to changing conditions or tasks without the need for human intervention.
- **Learning Efficiency**: It can potentially learn more efficiently and effectively from experience.

## Discussion Points
- **Feasibility**: How feasible is it to implement the Tabula Rasa approach within our project's domain?
- **Resource Requirements**: What computational resources, data, or infrastructure would be needed?
- **Evaluation Metrics**: How do we measure the success and progress of the Tabula Rasa learning process?
- **Use Cases**: In what scenarios or domains could this approach be most beneficial?
- **Long-Term Goals**: What are the long-term objectives and expected outcomes of implementing Tabula Rasa learning?

Let's discuss the feasibility and potential implementation strategies for this approach in our project.

**Comment by asdfjkl** [comment]
Good luck with your project! Note that btw in several taxonomies, the deep reinforcement algorithm that is used by AlphaGo Zero/Alpha Zero is already considered a tabula rasa approach.

**Comment by severeduck** [comment]
@asdfjkl thanks for your kind words. i took a step back and am currently looking at https://github.com/severeduck/quantumchess. feel free to open a merge request should you come up with an idea
